package auction

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"strconv"
	t "tauras/types"
	"time"

	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
	"github.com/gin-gonic/gin"
)

type BidRequest struct {
	Bidid string `json:"Bidid"` //gonna be generated by the system
	Auctionid string `json:"Auctionid" binding:"required"` //mandatory
	Userid string `json:"Userid" binding:"required"` //mandatory
	Price float64 `json:"Price" binding:"required"` //mandatory
	Timestamp int64 `json:"Timestamp"` //gonna be generated by the system
}

func strPtr(s string) *string { return &s }

func BidHandler(c *gin.Context, ctx *t.AppContext) {
	s := ctx.Session.RequireSession(c)
	db := ctx.DB
	p := ctx.KafkaProducer

	if s == nil {
		return
	}

	var req BidRequest
	if err := c.ShouldBindBodyWithJSON(&req); err != nil {
		c.JSON(400, gin.H{"error": "body did not match: " + err.Error()})
		return
	}

	req.Bidid = "bid-" + fmt.Sprint(req.Userid) + "-" + fmt.Sprint(req.Auctionid)
	req.Timestamp = time.Now().Unix()
	fmt.Println("Received bid request: \n", req)

	auctionID, err := strconv.ParseInt(req.Auctionid, 10, 64)
	if err != nil {
		c.JSON(400, gin.H{"error": "Invalid auction id"})
		return
	}

	// Enforce auction end time (IST / Asia-Kolkata).
	var endTime time.Time
	if err := db.QueryRow("SELECT end_time FROM auctions WHERE id = ?", auctionID).Scan(&endTime); err != nil {
		if err == sql.ErrNoRows {
			c.JSON(404, gin.H{"error": "Auction not found"})
			return
		}
		log.Printf("error selecting auction end_time: %v", err)
		c.JSON(500, gin.H{"error": "Failed to validate auction end time"})
		return
	}

	loc, locErr := time.LoadLocation("Asia/Kolkata")
	if locErr != nil {
		log.Printf("error loading IST location: %v", locErr)
		c.JSON(500, gin.H{"error": "Internal server error"})
		return
	}

	nowIST := time.Now().In(loc)
	endIST := endTime.In(loc)
	if !nowIST.Before(endIST) {
		c.JSON(400, gin.H{"error": "Auction has already ended"})
		return
	}
	//do a atomic transaction to ensure we get the correct max bid and insert the new bid without race conditions
	//1st check if the new bid is higher than current_price from the auctions table and then update the bid if it else rollback
	tx , err := db.Begin()
	if err != nil {
		log.Printf("error starting transaction: %v", err)
		c.JSON(500 , err)
		return;
	}
	res , err := tx.Exec(
		"Update auctions set current_price = ? where id = ? and current_price < ?",
		req.Price, auctionID, req.Price,
	);

	if err != nil {
		tx.Rollback()
		log.Printf("error updating auction current price: %v", err)
		c.JSON(500 , err)
		return;
	}
	_ , err = tx.Exec(
		"INSERT INTO bids (auction_id, user_id, price) VALUES (?, ?, ?)",
		auctionID, s.UserID, req.Price,
	)
	if err != nil {
		tx.Rollback()
		c.JSON(500 , err);
		return;
	}
	rowsaffected , err := res.RowsAffected();
	if err != nil {
		tx.Rollback()
		c.JSON(500, err)
	}
	if rowsaffected == 0 {
		tx.Rollback();
		c.JSON(400, gin.H{"error": "Bid was not high enough to update the current bid"})
		return;
	}
	if err := tx.Commit(); err != nil {
		log.Printf("error committing transaction: %v", err)
		c.JSON(500, err)
		return;
	}

	/* old code without transaction (bad code do not use)
	var maxPrice sql.NullFloat64
	err = db.QueryRow(
		"SELECT COALESCE(MAX(price), 0) FROM bids WHERE auction_id = ?",
		auctionID,
	).Scan(&maxPrice)
	if err != nil {
		log.Printf("error getting max bid: %v", err)
		c.JSON(500, gin.H{"error": "Failed to update bid"})
		return
	}
	currentMax := 0.0
	if maxPrice.Valid {
		currentMax = maxPrice.Float64
	}
	if req.Price <= currentMax {
		c.JSON(400, gin.H{"error": "Bid was not high enough to update the current bid"})
		return
	}

	_, err = db.Exec(
		"INSERT INTO bids (auction_id, user_id, price) VALUES (?, ?, ?)",
		auctionID, s.UserID, req.Price,
	)
	if err != nil {
		log.Printf("error inserting bid: %v", err)
		c.JSON(500, gin.H{"error": "Failed to update bid"})
		return
	}
	*/

	msgbytes, err := json.Marshal(req)
	if err != nil {
		log.Println("Failed to marshal bid request: ", err)
	}
	if p != nil {
		p.Produce(
			&kafka.Message{
				TopicPartition: kafka.TopicPartition{Topic: strPtr("bids"), Partition: kafka.PartitionAny},
				Value:          msgbytes,
			}, nil,
		)
	}

	c.JSON(200, gin.H{"success": "1"})
}
