package main

import (
	"fmt"
	"time"

	"github.com/gin-gonic/gin"
)

type BidRequest struct {
	Bidid string `json:"Bidid"` //gonna be generated by the system
	Auctionid string `json:"Auctionid" binding:"required"` //mandatory
	Userid string `json:"Userid" binding:"required"` //mandatory
	Price float64 `json:"Price" binding:"required"` //mandatory
	Timestamp int64 `json:"Timestamp"` //gonna be generated by the system
}

func main(){
	r := gin.Default();
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, "helloworld");
	});
	r.POST("/bid", func(c *gin.Context) {
		//check if the request body is valid
		var req BidRequest;

		if err := c.ShouldBindBodyWithJSON(&req); err != nil {
			c.JSON(400, gin.H{"error body did not match": err.Error()});
			return 
		}
		//generate bidid and timestamp
		req.Bidid = "bid-" + fmt.Sprint(req.Userid) + "-" + fmt.Sprint(req.Auctionid);
		req.Timestamp = time.Now().Unix();
		req.Bidid = "123456789"; //for testing purposes only, should be generated by the system
		fmt.Println("Received bid request: \n", req);
		c.JSON(200 , "success");
	});
	r.Run(":8080");
}